version: '3.9'
services:
  wordpress:
    build:
      context: ./requirements/wordpress/
    restart: always
    container_name: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb

  mariadb:
      container_name: mariadb
      build: ./requirements/mariadb/
      networks:
            - inception
      restart: always
      env_file:
          -  ./.env
      volumes:
        - base_data:/var/lib/mysql
      #environment:
      #   MYSQL_ROOT_PASSWORD: root
      #   MYSQL_DATABASE: mariadb
      #   MYSQL_USER: orbiay
      #   MYSQL_PASSWORD: root

  nginx:
      container_name: nginx
      build: ./requirements/nginx/ 
      networks:
            - inception
      restart: unless-stopped
      ports:
              - "443:443"
      volumes:
               - wp_data:/var/www/wordpress
      depends_on:
          - wordpress
# volumes:
#    wp_data:
#    base_data:

volumes:
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/yel-aoun/data/wp_data/
  base_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/yel-aoun/data/base_data/
networks:
  inception:
